name: Build RSDKv4
on:
  push:
    branches:
      - master
      - main
      - linux-actions
      - MainMenuRewrite

jobs:
  v4-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libogg-dev libvorbis-dev libsdl2-dev libglew-dev libtinyxml2-dev libstb-dev
      - name: Build RSDKv4
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: v4-linux
          path: bin
